# Generated by Django 5.1.1 on 2024-09-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
