# Generated by Django 5.1.1 on 2024-09-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_booking_duration_booking_picked_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
